name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildAndroid:
    name: Build Unity Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-
            
      - uses: xrtk/unity-setup@v7
        with:
          build-targets: $ANDROID_BUILD_TARGET
          
      - name: Activate Unity License
        uses: xrtk/activate-unity-license@v5
        with:
          license-type: 'Personal'
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}

      - name: Build Android APK
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: $ANDROID_BUILD_TARGET
          buildName: ArmyComander
          buildPath: build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/Android/ArmyComander.apk

      - name: Return Unity License
        if: always()
        uses: game-ci/unity-return-license@v2
