name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildAndroid:
    name: Build Unity Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo apt-get clean
          df -h
          
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-ArmyComander-${{ vars.ANDROID_BUILD_TARGET }}
          restore-keys: |
            Library-ArmyComander-
            Library-
            
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Android APK
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.0.51f1
          targetPlatform: ${{ vars.ANDROID_BUILD_TARGET }}
          buildName: ArmyComander
          buildsPath: Build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArmyComander
          path: Build/${{ env.ANDROID_BUILD_TARGET }}

      - name: Return Unity License
        if: always()
        uses: game-ci/unity-return-license@v2
